#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/C1N

PRODUCT_COPY_FILES += \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_1440x1080.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_1440x1080.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_1920x1080.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_1920x1080.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_2048x1536.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO1000_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO1000_864x480.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_1440x1080.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_1440x1080.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_1920x1080.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_1920x1080.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_2048x1536.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/front/ISO800_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/front/ISO800_864x480.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_2688x1512.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_3200x2400.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_3840x2160.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO1000_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO1000_4608x3456.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_2688x1512.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_3200x2400.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_3840x2160.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO400_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO400_4608x3456.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_2688x1512.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_3200x2400.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_3840x2160.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO500_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO500_4608x3456.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_2688x1512.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_3200x2400.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_3840x2160.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO640_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO640_4608x3456.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_1280x720.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_2592x1944.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_2688x1512.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_3200x2400.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_3840x2160.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/C1N/ncf/rear/ISO800_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/C1N/ncf/rear/ISO800_4608x3456.ncf \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Bluetooth_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/General_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Global_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Handset_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Hdmi_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Headset_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/Speaker_cal.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/C1N/sdm660-snd-card-c1n-A/workspaceFile.qwsp \
    vendor/nokia/C1N/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/C1N/proprietary/vendor/etc/audio_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/camera/calibration_test.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calibration_test.bin \
    vendor/nokia/C1N/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/camera/s5k2p7sx_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2p7sx_chromatix.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/camera/s5k4e8_c1n_front_2nd_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4e8_c1n_front_2nd_chromatix.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/camera/s5k4e8_c1n_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4e8_c1n_front_chromatix.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/nokia/C1N/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/nokia/C1N/proprietary/vendor/etc/sensors/sensor_def_qcomdev_c1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev_c1.conf \
    vendor/nokia/C1N/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nokia/C1N/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/nokia/C1N/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/nokia/C1N/proprietary/vendor/etc/wifi/bdf/bdwlan_C1N_cal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_C1N_cal.bin \
    vendor/nokia/C1N/proprietary/vendor/etc/wifi/bdf/bdwlan_def.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_def.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/a508_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.b01 \
    vendor/nokia/C1N/proprietary/vendor/firmware/a508_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.mdt \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b00 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b01 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b02 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b03 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b04 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b05 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b06 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.mdt \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b00 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b01 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b02 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b03 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b04 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b05 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b06 \
    vendor/nokia/C1N/proprietary/vendor/firmware/cmnlib64.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.mdt \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_config.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config.cfg \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_config_hlt.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_hlt.cfg \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_config_hlt_ctl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_hlt_ctl.cfg \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_config_oflim.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_oflim.cfg \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_config_truly.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_truly.cfg \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_firmware_hlt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_hlt.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_firmware_hlt_ctl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_hlt_ctl.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_firmware_oflim.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_oflim.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/goodix_firmware_truly.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_truly.bin \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b00 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b01 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b02 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b03 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b04 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b05 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b06 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.b07 \
    vendor/nokia/C1N/proprietary/vendor/firmware/gxfp5288_c1n.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp5288_c1n.mdt \
    vendor/nokia/C1N/proprietary/vendor/usr/keylayout/goodix_fp.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/goodix_fp.kl

PRODUCT_PACKAGES += \
    libsensor1 \
    libsensor_reg \
    sensor_calibrate \
    sensors.ssc \
    camera.sdm660 \
    keystore.sdm660 \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_bu64297_c1n \
    libactuator_pseudo \
    libadiertac \
    libadm \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libaoa \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_night_shot \
    libarcsoft_picselfie_algorithm \
    libarcsoft_smart_denoise \
    libaudcal \
    libaudioalsa \
    libchromatix_s5k2p7sx_4k_preview_3a \
    libchromatix_s5k2p7sx_4k_video_3a \
    libchromatix_s5k2p7sx_common \
    libchromatix_s5k2p7sx_cpp_hfr_120 \
    libchromatix_s5k2p7sx_cpp_hfr_60 \
    libchromatix_s5k2p7sx_cpp_hfr_90 \
    libchromatix_s5k2p7sx_cpp_liveshot \
    libchromatix_s5k2p7sx_cpp_preview \
    libchromatix_s5k2p7sx_cpp_snapshot \
    libchromatix_s5k2p7sx_cpp_video \
    libchromatix_s5k2p7sx_cpp_video_4k \
    libchromatix_s5k2p7sx_default_preview_3a \
    libchromatix_s5k2p7sx_default_video_3a \
    libchromatix_s5k2p7sx_hfr_120 \
    libchromatix_s5k2p7sx_hfr_120_3a \
    libchromatix_s5k2p7sx_hfr_60 \
    libchromatix_s5k2p7sx_hfr_60_3a \
    libchromatix_s5k2p7sx_hfr_90 \
    libchromatix_s5k2p7sx_hfr_90_3a \
    libchromatix_s5k2p7sx_postproc \
    libchromatix_s5k2p7sx_preview \
    libchromatix_s5k2p7sx_snapshot \
    libchromatix_s5k2p7sx_snapshot_longexposure \
    libchromatix_s5k2p7sx_versions \
    libchromatix_s5k2p7sx_video \
    libchromatix_s5k2p7sx_video_4k \
    libchromatix_s5k2p7sx_zsl_preview_3a \
    libchromatix_s5k2p7sx_zsl_video_3a \
    libchromatix_s5k4e8_c1n_front_2nd_4k_preview_3a \
    libchromatix_s5k4e8_c1n_front_2nd_4k_video_3a \
    libchromatix_s5k4e8_c1n_front_2nd_common \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_hfr_120 \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_hfr_60 \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_hfr_90 \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_liveshot \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_preview \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_snapshot \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_video \
    libchromatix_s5k4e8_c1n_front_2nd_cpp_video_4k \
    libchromatix_s5k4e8_c1n_front_2nd_default_preview_3a \
    libchromatix_s5k4e8_c1n_front_2nd_default_video \
    libchromatix_s5k4e8_c1n_front_2nd_default_video_3a \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_120 \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_120_3a \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_60 \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_60_3a \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_90 \
    libchromatix_s5k4e8_c1n_front_2nd_hfr_90_3a \
    libchromatix_s5k4e8_c1n_front_2nd_liveshot \
    libchromatix_s5k4e8_c1n_front_2nd_postproc \
    libchromatix_s5k4e8_c1n_front_2nd_preview \
    libchromatix_s5k4e8_c1n_front_2nd_snapshot \
    libchromatix_s5k4e8_c1n_front_2nd_versions \
    libchromatix_s5k4e8_c1n_front_2nd_video_4k \
    libchromatix_s5k4e8_c1n_front_2nd_zsl_preview_3a \
    libchromatix_s5k4e8_c1n_front_2nd_zsl_video_3a \
    libchromatix_s5k4e8_c1n_front_4k_preview_3a \
    libchromatix_s5k4e8_c1n_front_4k_video_3a \
    libchromatix_s5k4e8_c1n_front_common \
    libchromatix_s5k4e8_c1n_front_cpp_hfr_120 \
    libchromatix_s5k4e8_c1n_front_cpp_hfr_60 \
    libchromatix_s5k4e8_c1n_front_cpp_hfr_90 \
    libchromatix_s5k4e8_c1n_front_cpp_liveshot \
    libchromatix_s5k4e8_c1n_front_cpp_preview \
    libchromatix_s5k4e8_c1n_front_cpp_snapshot \
    libchromatix_s5k4e8_c1n_front_cpp_video \
    libchromatix_s5k4e8_c1n_front_cpp_video_4k \
    libchromatix_s5k4e8_c1n_front_default_preview_3a \
    libchromatix_s5k4e8_c1n_front_default_video \
    libchromatix_s5k4e8_c1n_front_default_video_3a \
    libchromatix_s5k4e8_c1n_front_hfr_120 \
    libchromatix_s5k4e8_c1n_front_hfr_120_3a \
    libchromatix_s5k4e8_c1n_front_hfr_60 \
    libchromatix_s5k4e8_c1n_front_hfr_60_3a \
    libchromatix_s5k4e8_c1n_front_hfr_90 \
    libchromatix_s5k4e8_c1n_front_hfr_90_3a \
    libchromatix_s5k4e8_c1n_front_liveshot \
    libchromatix_s5k4e8_c1n_front_postproc \
    libchromatix_s5k4e8_c1n_front_preview \
    libchromatix_s5k4e8_c1n_front_snapshot \
    libchromatix_s5k4e8_c1n_front_versions \
    libchromatix_s5k4e8_c1n_front_video_4k \
    libchromatix_s5k4e8_c1n_front_zsl_preview_3a \
    libchromatix_s5k4e8_c1n_front_zsl_video_3a \
    libdepthmapwrapper \
    libfih_camera_effect \
    libflash_dummy_flash \
    libflash_pmic \
    libhal_dbg \
    libimage_matting \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k2p7sx \
    libmmcamera_s5k2p7sx_gt24c64_truly_eeprom \
    libmmcamera_s5k4h8 \
    libmmcamera_s5k4h8_eeprom \
    libmmcamera_s5k4h8_holitech_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libpn553_fw \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    fingerprint.gxfp5288_c1n \
    gatekeeper.sdm660 \
    libgf_ca_gxfp5288_c1n \
    libgf_hal_gxfp5288_c1n \
    libgoodixhwfingerprint_gxfp5288_c1n \
    libvendor.goodix.hardware.fingerprint@1.0 \
    libvendor.goodix.hardware.fingerprintextension@1.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libvpp_svc_skel \
    cnss-daemon \
    mm-qcamera-app \
    sensors.qti
